export interface ModelInfo { id: string; name: string; efforts: string[]; default_effort: string | null; structured_output: boolean; effort_source: string }
export interface ProviderInfo { id: string; connected: boolean; message: string; plan?: string; limits?: unknown }
export interface Metrics { calls: number; input_tokens: number; output_tokens: number; cached_input_tokens: number; reasoning_output_tokens: number; total_tokens: number; known_cost_usd: number; cost_usd: number | null; unknown_cost_calls: number; unknown_usage_calls: number; mean_latency_ms: number | null; deaths: number; boss_events: number; game_completions: number; skill_failures: number; interventions: number; trajectories_learned: number; trajectory_replays: number; trajectory_replay_successes: number }
export interface RunConfig { provider: string; model: string; effort: string | null; goal: string; memory_mode: string; max_calls: number; max_tokens: number; max_cost_usd: number; max_output_tokens: number; max_runtime_s: number; checkpoint_label: string }
export interface ActorObservation { actor_id: number; name: string; description: string; category: number; params: number; position: number[]; focus_position: number[] | null; distance: number; targeted: boolean; drawn: boolean; text_id: number | null }
export interface DialogueState { active: boolean; text_id: number | null; text: string; state: string; state_code: number; message_mode: number; can_advance: boolean; choice_count: number; choice_index: number; choices: string[]; speaker: ActorObservation | null }
export interface EquipmentObservation { item_id: number; name: string; equipment_type: 'sword' | 'shield' | 'tunic' | 'boots'; value: number; equipped: boolean }
export interface ProgressState { quest_items: string[]; owned_equipment: string[]; equipment: EquipmentObservation[]; upgrade_levels: Record<string, number>; heart_pieces: number; skull_tokens: number; magic_acquired: boolean; double_magic: boolean; double_defense: boolean; map_index: number; dungeon_items: string[]; small_keys: number }
export interface ContextAction { code: number; label: string }
export interface PauseMenuState { active: boolean; ready: boolean; state: number; transition_state: number; page_index: number; cursor_special_pos: number; cursor_point: number[]; cursor_item: number[]; cursor_slot: number[]; named_item: number | null; prompt_choice: number }
export interface InventoryObservation { slot: number; item_id: number; name: string; ammo: number | null }
export interface GameState { source: string; seq: number; scene_epoch: number; scene: number; scene_name: string; room: number; entrance_index: number; day_time: number; is_night: boolean; in_game: boolean; paused: boolean; cutscene_active: boolean; game_over_state: number; ocarina_mode: number; ocarina_action: number; last_played_song: number; player: { health: number; max_health: number; rupees: number; magic: number; position: number[]; yaw: number; speed_xz: number; floor_height: number; wall_yaw: number; bg_check_flags: number; y_dist_to_water: number; age: string } | null; inventory: number[]; inventory_named: InventoryObservation[]; message_id: number | null; dialogue: DialogueState; progress: ProgressState; context_action: ContextAction; pause_menu: PauseMenuState; target_actor: ActorObservation | null; nearby_actors: ActorObservation[] }
export interface Trajectory { id: string; from_scene: number; from_room: number; to_scene: number; to_room: number; actions: Array<{skill: string; args: Record<string, unknown>}>; successes: number; failures: number; updated_at: number }
export interface WorldEdge { id: string; from_scene: number; from_scene_name: string; from_room: number; from_position: number[]; to_scene: number; to_scene_name: string; to_room: number; to_position: number[]; entrance_index: number; traversals: number; updated_at: number }
export interface Snapshot { status: string; reason: string; run_id: string | null; config: RunConfig | null; pending_switch: RunConfig | null; metrics: Metrics | null; elapsed_s: number; last_decision: { goal: string; summary: string; skill: string } | null; last_result: { status: string; reason: string; distance: number | null; yaw_delta?: number | null; health_lost: number | null } | null; events: Array<{kind: string; data: Record<string, unknown>; at: number}>; bridge: { connected: boolean; state: GameState | null; last_seen_age_s: number | null }; memory: Array<{id: string; scene: number; note: string; created_at: number}>; trajectories: Trajectory[]; world_edges: WorldEdge[] }
export interface RunRow { id: string; created_at: number; status: string; config: RunConfig; source: string; mixed: boolean; assisted: boolean; metrics: Metrics }
export interface Skill { id: string; name: string; status: string; version: string | null }
