export interface ModelInfo { id: string; name: string; efforts: string[]; default_effort: string | null; structured_output: boolean; effort_source: string }
export interface ProviderInfo { id: string; connected: boolean; message: string; plan?: string; limits?: unknown }
export interface Metrics { calls: number; input_tokens: number; output_tokens: number; cached_input_tokens: number; reasoning_output_tokens: number; total_tokens: number; known_cost_usd: number; cost_usd: number | null; unknown_cost_calls: number; unknown_usage_calls: number; mean_latency_ms: number | null; deaths: number; boss_events: number; skill_failures: number; interventions: number; trajectories_learned: number; trajectory_replays: number; trajectory_replay_successes: number }
export interface RunConfig { provider: string; model: string; effort: string | null; goal: string; memory_mode: string; max_calls: number; max_tokens: number; max_cost_usd: number; max_output_tokens: number; max_runtime_s: number; checkpoint_label: string }
export interface GameState { source: string; seq: number; scene: number; room: number; in_game: boolean; paused: boolean; player: { health: number; max_health: number; rupees: number; magic: number; position: number[]; yaw: number; age: string } | null; inventory: number[]; message_id: number | null }
export interface Trajectory { id: string; from_scene: number; from_room: number; to_scene: number; to_room: number; actions: Array<{skill: string; args: Record<string, unknown>}>; successes: number; failures: number; updated_at: number }
export interface Snapshot { status: string; reason: string; run_id: string | null; config: RunConfig | null; pending_switch: RunConfig | null; metrics: Metrics | null; elapsed_s: number; last_decision: { goal: string; summary: string; skill: string } | null; last_result: { status: string; reason: string; distance: number | null; yaw_delta?: number | null; health_lost: number | null } | null; events: Array<{kind: string; data: Record<string, unknown>; at: number}>; bridge: { connected: boolean; state: GameState | null; last_seen_age_s: number | null }; memory: Array<{id: string; scene: number; note: string; created_at: number}>; trajectories: Trajectory[] }
export interface RunRow { id: string; created_at: number; status: string; config: RunConfig; source: string; mixed: boolean; assisted: boolean; metrics: Metrics }
export interface Skill { id: string; name: string; status: string; version: string | null }
